#DECLARE PerfInputPath string = "/local/AdsOI/UnifiedLayerPerf/%Y/%m/%d/OrderItemPerf.ss?date={0}...{1}"; 

TargetOrderItemPerf = 
    SELECT LogDate,
           Impressions,
           Clicks,
           Math.Round(RevenueUSD, 2) AS Revenue,
           (Impressions == 0 ? 0 : Math.Round((Clicks * 1.0f / Impressions), 4)) AS CTR,
           (Clicks == 0 ? 0 : Math.Round((RevenueUSD / Clicks), 2)) AS CPC
    FROM (SSTREAM @PerfInputPath)
    WHERE OrderItemId == "{2}";
OUTPUT TargetOrderItemPerf TO CONSOLE;
